<?php
/**
 * Created by www.vuecmf.com
 * User: emei8 <386196596@qq.com>
 * Date: 2019/7/1
 * Time: 22:59
 */

namespace app\api\service;


use think\Db;

class AuthItemService extends BaseService
{
    protected $prefix; //表前缀

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = model('AuthItem'); //初始化模型
        $this->prefix = config('database.prefix');
    }



}
