<?php
/**
 * Created by www.vuecmf.com
 * User: 386196596@qq.com
 * Date: 2018/11/7
 * Time: 23:56
 */

namespace app\api\controller;



use think\Db;
use think\Exception;
use think\facade\Request;
use think\facade\Validate;


class Menu extends Base
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = model('AuthMenu');
        if(Request::action() == 'save'){
            $this->validate = new \app\api\validate\AuthMenu();
        }

    }

    /**
     * 获取后台所有菜单
     * @return \think\response\Json
     */
    public function index()
    {
        try{
            //菜单权限
            $auth_list = Db::name('auth_item_child')->whereIn('parent',$this->user['role'])->column('child');
            $auth_menu_data = Db::name('auth_item_menu')->whereIn('item_name',$auth_list)->where('status',1)->column('menu_id','id');

            $item_menu_id_arr = array_keys($auth_menu_data);
            $menu_id_arr = array_values($auth_menu_data);

            //操作项权限
            $operate_id_arr = Db::name('auth_item_menu_operate')->whereIn('item_menu_id',$item_menu_id_arr)->where('status',1)->column('operate_id');

            $nav_menu_tree = make_menu_tree(0,0,$menu_id_arr,$operate_id_arr);
            $menu_data['nav_menu'] = $nav_menu_tree;
            reset($nav_menu_tree);
            $first_key = key($nav_menu_tree);
            $menu_data['active'] = (string)$first_key;
            unset($nav_menu_tree);

            return api_return($menu_data);
        }catch (Exception $e){
            return api_return('','拉取菜单失败!'.$e->getMessage(),1002);
        }


    }






}
